[uat-webservers]
172.31.30.99 ansible_ssh_user='ec2-user' 

172.31.24.191 ansible_ssh_user='ec2-user' 

[nfs]
172.31.22.132 ansible_ssh_user='ec2-user'

[webservers]
172.31.22.88 ansible_ssh_user='ec2-user'
172.31.24.121 ansible_ssh_user='ec2-user'

[db]
172.31.25.209 ansible_ssh_user='ubuntu'

[lb]
172.31.19.98 ansible_ssh_user='ubuntu'
