---
- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  tags:
    - always
 
- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import webserver file
  import_playbook: ../static-assignments/webservers.yml

- name: import database file
  import_playbook: ../static-assignments/db.yml


- name: import Loadbalancers assignment
  import_playbook: ../static-assignments/lb.yml
  when: load_balancer_is_required 


